---
- hosts: all
  remote_user: root
  vars_files:
    - ../var/ubuntu.yml
  tasks:
    - name: add public key to host
      copy:
        src: ../file/authorized_keys
        dest: /root/.ssh/authorized_keys
    - name: configure modules
      copy:
        src: ../file/modules
        dest: /etc/modules

- hosts: controller
  remote_user: root
  vars_files:
    - ../var/ubuntu.yml
  tasks:
    - name: install iptables package
      apt:
        name: iptables
        state: present
    - name: configure network
      template:
        src: ../template/bifrost/controller.interface.j2
        dest: /etc/network/interfaces
      notify:
        - restart network service
  handlers:
    - name: restart network service
      shell: "/sbin/ifconfig ens3 0 &&/sbin/ifdown -a && /sbin/ifup -a"

- hosts: compute
  remote_user: root
  vars_files:
    - ../var/ubuntu.yml
  tasks:
    - name: install iptables package
      apt:
        name: iptables
        state: present
    - name: configure network
      template:
        src: ../template/bifrost/compute.interface.j2
        dest: /etc/network/interfaces
      notify:
        - restart network service
  handlers:
    - name: restart network service
      shell: "/sbin/ifconfig ens3 0 &&/sbin/ifdown -a && /sbin/ifup -a"

- hosts: compute01
  remote_user: root
  tasks:
    - name: make nfs dir
      file: "dest=/images mode=777 state=directory"
    - name: configure sdrvice
      shell: "echo 'nfs        2049/tcp' >>  /etc/services && echo 'nfs        2049/udp' >>  /etc/services"
    - name: configure NFS
      copy:
        src: ../file/exports
        dest: /etc/exports
      notify:
        - restart nfs service
  handlers:
    - name: restart nfs service
      service: name=nfs-kernel-server state=restarted
